import { Body, Controller, HttpCode, Logger, Post, Req, UseGuards } from '@nestjs/common';
import { ApiBody, ApiHeader, ApiOperation, ApiResponse, ApiTags } from '@nestjs/swagger';
import type { FastifyRequest } from 'fastify';
import { z } from 'zod';
import { RawResponse } from '../../../core/common/decorators/raw-response.decorator';
import { ZodValidationPipe } from '../../../core/common/pipes/zod-validation.pipe';
import { UcApiKeyGuard } from '../guards';
import { UcEventLogService } from '../services/event-log.service';
import { UcFeatureFlagsService } from '../services/feature-flags.service';
import { UcOrderItemMapService } from '../services/order-item-map.service';
import { UcRatioApiService } from '../services/uc-ratio-api.service';

const cancelSchema = z.object({
  orderId: z.string(),
  orderItems: z
    .array(
      z.object({
        orderItemId: z.string(),
        productId: z.string(),
        variantId: z.string(),
        quantity: z.number(),
      }),
    )
    .min(1),
});
type CancelRequest = z.infer<typeof cancelSchema>;

@ApiTags('unicommerce')
@Controller('unicommerce/api/v1')
@UseGuards(UcApiKeyGuard)
@RawResponse()
export class UcOrderCancelController {
  private readonly logger = new Logger(UcOrderCancelController.name);

  constructor(
    private readonly orderItemMap: UcOrderItemMapService,
    private readonly ratio: UcRatioApiService,
    private readonly eventLog: UcEventLogService,
    private readonly featureFlags: UcFeatureFlagsService,
  ) {}

  @Post('orders/cancel')
  @HttpCode(200)
  @ApiOperation({
    summary: 'Cancel order items',
    description:
      'Unicommerce calls this when the seller cancels an order inside UC.',
  })
  @ApiHeader({
    name: 'apikey',
    required: true,
    description: 'Access token issued by /authToken (TTL ~48h). Identifies the merchant.',
    example: 'pX7vK2mQ9nL4wR8tY5bH1cJ3dF6gS0zA7eU2iM4k',
  })
  @ApiBody({
    required: true,
    description:
      '`orderId` is the sale order code UC knows (surrogate: the Ratio order id used at order push). ' +
      '`orderItems` lists exactly which items to cancel — `quantity` is the cancelled count.',
    schema: {
      type: 'object',
      properties: {
        orderId: {
          type: 'string',
          example: 'gid://shopify/Order/5432109876543',
          description: 'Sale order code as UC knows it (the Ratio order id used at push).',
        },
        orderItems: {
          type: 'array',
          minItems: 1,
          items: {
            type: 'object',
            properties: {
              orderItemId: {
                type: 'string',
                example: '5f2a9c1e7b3d48f6a0c9e4b2d8f1a3c5e',
                description:
                  'UC-assigned order item id (32-char hex, generated by our order push).',
              },
              productId: {
                type: 'string',
                example: 'gid://shopify/Product/8123456789012',
                description: 'Our own Ratio product id.',
              },
              variantId: {
                type: 'string',
                example: 'gid://shopify/Variant/4345678901234',
                description: 'Our own Ratio variant id.',
              },
              quantity: {
                type: 'number',
                example: 2,
                description: 'Quantity being cancelled for this item.',
              },
            },
            required: ['orderItemId', 'productId', 'variantId', 'quantity'],
          },
        },
      },
      required: ['orderId', 'orderItems'],
    },
  })
  @ApiResponse({
    status: 200,
    description:
      'Per-item outcome in `orderItems[]`; `errorMessage` is present only on failures (`unknown orderItemId`, ' +
      '`failed to apply update`). `status` is SUCCESS when every item applied, PARTIAL_SUCCESS when some failed, ' +
      'FAILED when all failed. A disabled sync flag returns the SUCCESS shape with no errorMessage (accept-and-no-op).',
    schema: {
      type: 'object',
      properties: {
        status: { type: 'string', enum: ['SUCCESS', 'FAILED', 'PARTIAL_SUCCESS'] },
        orderItems: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              orderItemId: { type: 'string', example: '5f2a9c1e7b3d48f6a0c9e4b2d8f1a3c5e' },
              errorMessage: {
                type: 'string',
                example: 'unknown orderItemId',
                description: 'Present only on per-item failure.',
              },
            },
            required: ['orderItemId'],
          },
        },
      },
      required: ['status', 'orderItems'],
      example: {
        status: 'SUCCESS',
        orderItems: [{ orderItemId: '5f2a9c1e7b3d48f6a0c9e4b2d8f1a3c5e' }],
      },
    },
  })
  async cancel(
    @Req() req: FastifyRequest & { ucMerchantId: string },
    @Body(new ZodValidationPipe(cancelSchema)) body: CancelRequest,
  ) {
    // TRD §6: accept-and-no-op when disabled — never hard-reject.
    if (!(await this.featureFlags.isEnabled('cancel_sync', req.ucMerchantId))) {
      return {
        status: 'SUCCESS' as const,
        orderItems: body.orderItems.map((i) => ({ orderItemId: i.orderItemId })),
      };
    }
    const results: { orderItemId: string; errorMessage?: string }[] = new Array(
      body.orderItems.length,
    );
    const resolvedByOrder = new Map<
      string,
      { index: number; item: CancelRequest['orderItems'][number] }[]
    >();

    for (const [index, item] of body.orderItems.entries()) {
      const full = await this.orderItemMap.resolveFull(item.orderItemId);
      if (!full || full.merchantId !== req.ucMerchantId) {
        results[index] = { orderItemId: item.orderItemId, errorMessage: 'unknown orderItemId' };
        continue;
      }
      const group = resolvedByOrder.get(full.ratioOrderId) ?? [];
      group.push({ index, item });
      resolvedByOrder.set(full.ratioOrderId, group);
    }

    // TRD §2.7: all items of the order cancelled → whole-order cancel;
    // some items cancelled, others survive → PATCH the order with only the
    // surviving line items. Every item actually cancelled here is tagged
    // uc_originated so the outbound cancel-push loop-prevention check
    // (order-cancelled.handler.ts) knows this cancel already came from UC.
    for (const [ratioOrderId, group] of resolvedByOrder) {
      const cancellingIds = new Set(group.map((g) => g.item.orderItemId));
      const allItems = await this.orderItemMap.findByRatioOrder(req.ucMerchantId, ratioOrderId);
      const survivors = allItems.filter((i) => !cancellingIds.has(i.orderItemId));

      // Never let a downstream failure (Ratio API error, expired OAuth
      // token, network blip) escape as an uncaught exception — degrade to
      // a per-item error for every item in this order group, matching the
      // response shape this endpoint already reports real failures through.
      try {
        if (survivors.length === 0) {
          await this.ratio.cancelOrder(req.ucMerchantId, ratioOrderId);
        } else {
          await this.ratio.updateOrderLineItems(
            req.ucMerchantId,
            ratioOrderId,
            survivors.map((s) => ({ id: s.ratioLineItemId })),
          );
        }
      } catch (err) {
        this.logger.error({
          msg: 'failed to apply cancel to Ratio',
          ratioOrderId,
          err: err instanceof Error ? err.message : String(err),
        });
        for (const { index, item } of group) {
          results[index] = {
            orderItemId: item.orderItemId,
            errorMessage: 'failed to apply update',
          };
        }
        continue;
      }

      for (const { index, item } of group) {
        await this.orderItemMap.markSource(item.orderItemId, 'uc_originated');
        await this.orderItemMap.decrementRemainingQuantity(item.orderItemId, item.quantity);
        await this.orderItemMap.updateLastStatus(
          item.orderItemId,
          'CANCELLED',
          new Date().toISOString(),
        );
        results[index] = { orderItemId: item.orderItemId };
      }
    }

    const anyFailed = results.some((r) => r.errorMessage);
    const allFailed = results.every((r) => r.errorMessage);
    const response = {
      status: allFailed ? 'FAILED' : anyFailed ? 'PARTIAL_SUCCESS' : 'SUCCESS',
      orderItems: results,
    };
    try {
      await this.eventLog.record({
        merchantId: req.ucMerchantId,
        direction: 'inbound',
        flow: 'cancel',
        reference: body.orderId,
        result: allFailed ? 'failed' : anyFailed ? 'partial' : 'success',
        payload: body,
        response,
      });
    } catch (err) {
      this.logger.error({
        msg: 'event-log write failed for orders/cancel',
        err: err instanceof Error ? err.message : String(err),
      });
    }
    return response;
  }
}
