import { Body, Controller, HttpCode, Logger, Param, Post, Req, UseGuards } from '@nestjs/common';
import { ApiBody, ApiHeader, ApiOperation, ApiParam, ApiResponse, ApiTags } from '@nestjs/swagger';
import type { FastifyRequest } from 'fastify';
import { z } from 'zod';
import { RawResponse } from '../../../core/common/decorators/raw-response.decorator';
import { ZodValidationPipe } from '../../../core/common/pipes/zod-validation.pipe';
import { UcApiKeyGuard } from '../guards';
import { UcCredentialsService } from '../services/credentials.service';
import { UcEventLogService } from '../services/event-log.service';
import { UcFeatureFlagsService } from '../services/feature-flags.service';
import { UcOrderItemMapService } from '../services/order-item-map.service';
import { UcStatusMappingService } from '../services/status-mapping.service';
import { UcRatioApiService } from '../services/uc-ratio-api.service';

const statusSchema = z.object({
  // `IsReverse` — capital I — confirmed directly against
  // post_status_notification.html. Not a documentation nuance: the field
  // UC actually sends never matches a lowercase `isReverse` key.
  orderItems: z
    .array(
      z.object({
        orderItemId: z.string(),
        status: z.string(),
        IsReverse: z.boolean(),
        updated: z.string(),
      }),
    )
    .min(1),
});
type StatusRequest = z.infer<typeof statusSchema>;

@ApiTags('unicommerce')
@Controller('unicommerce/api/v1')
@UseGuards(UcApiKeyGuard)
@RawResponse()
export class UcStatusController {
  private readonly logger = new Logger(UcStatusController.name);

  constructor(
    private readonly orderItemMap: UcOrderItemMapService,
    private readonly statusMapping: UcStatusMappingService,
    private readonly ratio: UcRatioApiService,
    private readonly eventLog: UcEventLogService,
    private readonly credentials: UcCredentialsService,
    private readonly featureFlags: UcFeatureFlagsService,
  ) {}

  @Post('order/:orderId')
  @HttpCode(200)
  @ApiOperation({
    summary: 'Order status notification',
    description:
      '**Direction: Unicommerce → UC connector app.**\n\n' +
      "Called BY Unicommerce on every status change (no auto-retry on UC's side — a non-success response stops all " +
      "further status notifications for that order until the merchant manually retries inside UC). Each item's UC " +
      "`status` (+ `IsReverse`, capital I) is mapped onto Ratio's `fulfillment_status` (e.g. DISPATCHED/SHIPPED → " +
      '`fulfilled`, DELIVERED → `delivered`, RETURN_EXPECTED/RETURN_ACKNOWLEDGED → `return_in_progress`, and the ' +
      'reverse-map: CREATED/COURIER_ALLOCATED → `return_pickup_scheduled`, COMPLETE → `restocked`, NOT_RECEIVED → ' +
      '`return_failed`). Pre-dispatch forward statuses (CREATED, PICKED, PACKED, ...) map to no write. Out-of-order ' +
      'or duplicate updates are short-circuited. ' +
      'TOP-LEVEL `status` IS ALWAYS PINNED TO "SUCCESS" (confirmed by UC\'s team) — real per-item failures go into ' +
      '`orderItems[].errorMessage` (`unknown orderItemId`, `no_change`, `unrecognized status`, `failed to apply update`).',
  })
  @ApiHeader({
    name: 'apikey',
    required: true,
    description: 'Access token issued by /authToken (TTL ~48h). Identifies the merchant.',
    example: 'pX7vK2mQ9nL4wR8tY5bH1cJ3dF6gS0zA7eU2iM4k',
  })
  @ApiParam({
    name: 'orderId',
    required: true,
    description:
      'The sale order code this status notification belongs to (used as the event-log reference; item resolution happens via `orderItemId`).',
    example: 'gid://shopify/Order/5432109876543',
  })
  @ApiBody({
    required: true,
    description:
      'Status updates for one or more order items. `IsReverse` uses a CAPITAL I — that is exactly what UC sends ' +
      '(`post_status_notification.html`); a lowercase `isReverse` key never matches. `updated` is the ISO-8601 ' +
      'timestamp of the status change; older-than-stored duplicates short-circuit to a `no_change` per-item error.',
    schema: {
      type: 'object',
      properties: {
        orderItems: {
          type: 'array',
          minItems: 1,
          items: {
            type: 'object',
            properties: {
              orderItemId: {
                type: 'string',
                example: '5f2a9c1e7b3d48f6a0c9e4b2d8f1a3c5e',
                description:
                  'UC-assigned order item id (32-char hex, generated by our order push).',
              },
              status: {
                type: 'string',
                example: 'DISPATCHED',
                description:
                  'UC status vocabulary: CREATED, LOCATION_NOT_SERVICEABLE, PICKING, PICKED, PENDING_CUSTOMIZATION, CUSTOMIZATION_COMPLETE, PACKED, READY_TO_SHIP, SPLITTED, MERGED, MANIFESTED, DISPATCHED, SHIPPED, DELIVERED, RETURN_EXPECTED, RETURN_ACKNOWLEDGED, RETURNED, COURIER_ALLOCATED, COMPLETE, NOT_RECEIVED.',
              },
              IsReverse: {
                type: 'boolean',
                example: false,
                description:
                  'Capital-I `IsReverse` — true when this is a reverse (return) flow status.',
              },
              updated: {
                type: 'string',
                example: '2026-08-06T14:05:00+05:30',
                description: 'ISO-8601 timestamp of the status change.',
              },
            },
            required: ['orderItemId', 'status', 'IsReverse', 'updated'],
          },
        },
      },
      required: ['orderItems'],
    },
  })
  @ApiResponse({
    status: 200,
    description:
      'ALWAYS the success shape — top-level `status` is pinned to "SUCCESS" regardless of internal outcome (returning ' +
      'anything else makes UC stop sending status notifications for the order until manual retry). Real per-item ' +
      'failures are reported in `orderItems[].errorMessage` and still fully captured in our own event log.',
    schema: {
      type: 'object',
      properties: {
        status: { type: 'string', enum: ['SUCCESS'] },
        orderItems: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              orderItemId: { type: 'string', example: '5f2a9c1e7b3d48f6a0c9e4b2d8f1a3c5e' },
              errorMessage: {
                type: 'string',
                example: 'no_change',
                description:
                  'Present only on per-item failure (unknown orderItemId | no_change | unrecognized status | failed to apply update).',
              },
            },
            required: ['orderItemId'],
          },
        },
      },
      required: ['status', 'orderItems'],
      example: {
        status: 'SUCCESS',
        orderItems: [{ orderItemId: '5f2a9c1e7b3d48f6a0c9e4b2d8f1a3c5e' }],
      },
    },
  })
  async notify(
    @Param('orderId') orderId: string,
    @Req() req: FastifyRequest & { ucMerchantId: string },
    @Body(new ZodValidationPipe(statusSchema)) body: StatusRequest,
  ) {
    // TRD §6: accept-and-no-op when disabled — never hard-reject. The
    // notification-received signal still counts (§5 Signal B proof-of-life)
    // even though we skip applying anything to Ratio.
    if (!(await this.featureFlags.isEnabled('dispatch_status_sync', req.ucMerchantId))) {
      this.credentials.touchStatusNotification(req.ucMerchantId).catch(() => {});
      return {
        status: 'SUCCESS' as const,
        orderItems: body.orderItems.map((i) => ({ orderItemId: i.orderItemId })),
      };
    }
    const results: { orderItemId: string; errorMessage?: string }[] = [];

    for (const item of body.orderItems) {
      const full = await this.orderItemMap.resolveFull(item.orderItemId);
      if (!full || full.merchantId !== req.ucMerchantId) {
        results.push({ orderItemId: item.orderItemId, errorMessage: 'unknown orderItemId' });
        continue;
      }

      if (full.lastStatusUpdatedAt) {
        const incoming = new Date(item.updated).getTime();
        const stored = new Date(full.lastStatusUpdatedAt).getTime();
        if (incoming <= stored && full.lastStatus === item.status) {
          results.push({ orderItemId: item.orderItemId, errorMessage: 'no_change' });
          continue;
        }
      }

      let mapped: ReturnType<typeof this.statusMapping.map>;
      try {
        mapped = this.statusMapping.map(item.status, item.IsReverse);
      } catch (err) {
        this.logger.warn({
          msg: 'unrecognized Unicommerce status',
          orderItemId: item.orderItemId,
          status: item.status,
          isReverse: item.IsReverse,
          err: err instanceof Error ? err.message : String(err),
        });
        results.push({ orderItemId: item.orderItemId, errorMessage: 'unrecognized status' });
        continue;
      }
      // Never let a downstream failure (Ratio API error, expired OAuth
      // token, network blip) escape as an uncaught exception — this
      // endpoint must ALWAYS return the SUCCESS shape (see below), and an
      // unhandled 500 here would violate that just as badly as returning a
      // FAILED status would.
      try {
        if (mapped !== 'no_change') {
          await this.ratio.updateOrderStatus(req.ucMerchantId, full.ratioOrderId, mapped);
        }
        await this.orderItemMap.updateLastStatus(item.orderItemId, item.status, item.updated);
        results.push({ orderItemId: item.orderItemId });
      } catch (err) {
        this.logger.error({
          msg: 'failed to apply status update to Ratio',
          orderItemId: item.orderItemId,
          err: err instanceof Error ? err.message : String(err),
        });
        results.push({ orderItemId: item.orderItemId, errorMessage: 'failed to apply update' });
      }
    }

    this.credentials.touchStatusNotification(req.ucMerchantId).catch(() => {});

    const anyFailed = results.some((r) => r.errorMessage && r.errorMessage !== 'no_change');
    const allFailed = results.every((r) => r.errorMessage);
    // Confirmed directly by Unicommerce's team: this endpoint must ALWAYS
    // return the success shape, regardless of internal outcome. Returning
    // anything else means UC stops sending any further status notifications
    // for that order at all, until the merchant manually retries inside
    // Unicommerce — worse than a single lost update. Per-item failures still
    // go into `orderItems[].errorMessage` (that's the real, useful signal);
    // only the top-level `status` is pinned to SUCCESS. Real failures are
    // still fully captured for our own ops via the event-log write below.
    const response = {
      status: 'SUCCESS' as const,
      orderItems: results,
    };
    try {
      await this.eventLog.record({
        merchantId: req.ucMerchantId,
        direction: 'inbound',
        flow: 'status',
        reference: orderId,
        result: allFailed ? 'failed' : anyFailed ? 'partial' : 'success',
        payload: body,
        response,
      });
    } catch (err) {
      this.logger.error({
        msg: 'event-log write failed for order status notify',
        err: err instanceof Error ? err.message : String(err),
      });
    }
    return response;
  }
}
